dist: trusty
language: ruby
bundler_args: "--without production"
env:
- RAILS_ENV=test
cache: bundler
addons:
  chrome: stable
before_script:
- mkdir -p log
- export DB_HOST="http://127.0.0.1:5984"
- curl -X PUT $DB_HOST/_config/admins/primero -d '"primero"'
- cp config/travis/couchdb.yml config/
- cp config/travis/sunspot.yml config/
- cp config/travis/mailers.yml config/
- mkdir -p solr/data/test
- mkdir -p solr/cores/test
- cp config/travis/core.properties solr/cores/test/
script:
- bundle exec rake sunspot:solr:start
- bundle exec rspec spec
services:
- couchdb
branches:
- travisci
- maint_1.3
- maint_1.4
- maint_1.5
- maint_1.6
- development
- master
notifications:
  slack:
    rooms:
      secure: fBO6yW1muuxvopaCn5mvNC5OtcEaXIv/EMQr+VHlHI40JqgfDeqwezdGlqXP+XVw6MyKJ3eKEFu6Komgjz01DB7Hr9pyT3x/26mderFPV5FGj8Dftnj3E19kgoSAkONE4E/msU3Th8cQfSqGY74yYxZDnE0fnzbUaDit9KPJsWS4Jztc51gmCvFcov0pNIz2o5V45jNRd5XFwe/F8rBgmegr5grPl7D802hKzuI5WFvNvmtOSiS0+pMTE6PZRg2slo2u8PgC3zRx74Dt4vndg8XtwH9PQmJwwDsB2rIFOdvntPxoAwtzMUk1AvU8IMUmdZTYsPcf0rOQHjzrko+p6oz/ZoekDmzArc/OEcqmM1OvGWjI3FM+5pWS5Cnb9yP0/6d2tqsgEoTEz772sykVn0iZ0Fvyo73HlFIsq6USj8QEeU6xAG6TMb32Qez7dB9baXWxjVBj9QXVE4MTVzb5EBeB56lBmSpWV1/wVSYsQOdPRoObiK+B9YxahhZ0Y27hWQOHVIQ7ct22MzqriPB6ISN9kUmvNGAzktFINX4LtS6InzSzTqjwuWHMlToE+4B3KF4hQk426muvEhEYi2DJaiO2gGh5E7MR6mQt1vET190IZ8Y87tHZ6MuGdpP6/qEsAQxEFZUZhuWv18cfYpvXevWeZt5a8M5HseGe5RUQvb4=
    template:
    - 'Test run completed for %{repository}/*%{branch}*: <%{build_url}|%{message}> Run duration: %{elapsed_time}'
